# Generated by Django 3.2.12 on 2022-10-17 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='families',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Edad', models.IntegerField()),
                ('Fecha_Nacimiento', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
