# Generated by Django 3.2.12 on 2022-10-17 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('familyweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='families',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='families',
            old_name='Edad',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='families',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='families',
            name='Fecha_Nacimiento',
        ),
        migrations.AddField(
            model_name='families',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
